using Unity.Entities;
using UnityEngine;

/// <summary>
/// Managed component for the <see cref="PlayerResources"/> unmanaged component.
/// Attach this to a singleton management GameObject in the scene.
/// Holds the global resource count for the player.
/// </summary>
/// <remarks>
/// The component is a Singleton — only one instance should exist in the world.
/// </remarks>
class PlayerResourcesAuthoring : MonoBehaviour
{
    /// <summary>
    /// Starting amount of resources for the player.
    /// </summary>
    [Tooltip("Starting amount of resources for the player.")]
    public float startingResources = 100f;

    public static PlayerResourcesAuthoring Instance { get; private set; }

    /// <summary>
    /// Used for singleton logic.
    /// </summary>
    void Awake()
    {
        //Singleton logic
        if (Instance == null)
        {
            Instance = this;
        }
        else
        {
            Debug.LogError("Multiple instances of singleton found on " + this.gameObject.name);
            Destroy(this);
        }
    }
}

/// <summary>
/// Baker for the <see cref="PlayerResources"/> unmanaged component.
/// </summary>
class PlayerResourcesBaker : Baker<PlayerResourcesAuthoring>
{
    public override void Bake(PlayerResourcesAuthoring authoring)
    {
        Entity entity = GetEntity(TransformUsageFlags.Dynamic);
        AddComponent(entity, new PlayerResources
        {
            currentResources = authoring.startingResources
        });
    }
}

/// <summary>
/// Singleton component holding the player's global resource count.
/// "Resources" is the single in-game currency generated by Farm buildings
/// via <see cref="ResourceGenerator"/> and spent on building and training.
/// </summary>
/// <remarks>
/// The component is a Singleton, which should be obtained through
/// <see cref="SystemAPI.GetSingleton{T}()"/> or <see cref="SystemAPI.GetSingletonRW{T}()"/>.
/// </remarks>
public struct PlayerResources : IComponentData
{
    /// <summary>
    /// The player's current resource balance.
    /// Increased by <c>ResourceGenerationSystem</c> and decreased by building/training actions.
    /// </summary>
    public float currentResources;
}
